import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  siDroidManualSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
